version: "2.3"
services:

  backend:
    container_name: "backend"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "MYSQL_ROOT_PASSWORD=unpassword"
      - "MYSQL_DATABASE=db"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=unpassword"
      - "MYSQL_HOST=mydb"
      - "DEBUG=True"
      - "SECRET_KEY=44bxl39@+v%e#o=byz#+wfcf9r2qe=#&%3%@7yiyif9jvryb2v"
    restart: always

  mydb:
    container_name: "mydb"
    image: mysql:5.7
#    ports:
#      - '3306:3306'
    environment:
      - "MYSQL_ROOT_PASSWORD=unpassword"
      - "MYSQL_DATABASE=db"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=unserpassword"
    restart: always

  gateway:
    container_name: "gateway"
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - '5000:80'
      - '5443:443'
    volumes_from:
      - backend
    restart: always
