# Generated by Django 3.1.3 on 2020-11-20 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Vacation",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("U", "Sans solde"),
                            ("R", "RTT"),
                            ("N", "Congé payé"),
                        ],
                        default="N",
                        max_length=1,
                    ),
                ),
                ("start", models.DateField()),
                ("end", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
